### ISSUE TITLE
Symfony 4 template not found exception

### ISSUE THREAD

**Issue by mechanicalgux** [blackknight467/StarRatingBundle#21]
This bundle will trigger an exception Symfony 4.

https://github.com/blackknight467/StarRatingBundle/blob/08e7caf167232c96dd77182c603475ef9623290b/DependencyInjection/StarRatingExtension.php#L31

To solve this, change the line with:

```php
$resources = array_merge(array('@StarRatingBundle/rating.html.twig'), $resources);
```

Then add and alias to /config/packages/twig.yaml:

```yaml
twig:
  paths:
    '%kernel.project_dir%/templates': templates
    '%kernel.project_dir%/vendor/blackknight467/star-rating-bundle/blackknight467/StarRatingBundle/Resources/views': StarRatingBundle
```
